Improve make-plume-release script.

diff --git a/bin/make-plume-release b/bin/make-plume-release
--- a/bin/make-plume-release
+++ b/bin/make-plume-release
@@ -4,7 +4,6 @@
 
 script=$(basename $0)
 
-#pkg=$(basename $PWD)
 pkg="plume-lib"
 new=$1
 
@@ -28,13 +27,12 @@ if hg outgoing &> /dev/null; then
     exit 1
 fi
 
-if [[ ! -e java/plume.jar ]]; then
-    echo "Could not find java/plume.jar"
-    echo "Please run 'make jar' in plume-lib's top level directory."
+if [[ ! $(${JAVAC-"javac"} -version 2>&1) =~ "javac 1.7.0-jsr308" ]]; then
+    echo "Please use the JSR308 compiler to make a release."
     exit 1
 fi
 
-echo "Going to create release $new of $pkg"
+echo "Going to release version $new of $pkg."
 echo -n "Is this correct? [y/n]: "
 read answer
 
@@ -43,60 +41,80 @@ if [[ ! ($ans = "y" || $ans = "Y") ]]; then
     exit 1
 fi
 
+release="$pkg-$new"
+release_tar="$release.tar.gz"
+
+echo "[1/6] Creating Mercurial tag 'v$new'."
 if ! hg tag v$new &> /dev/null; then
     echo "Failed to create Mercurial tag 'v$new'."
     echo "Run 'hg tags' to check if the tag already exists."
     exit 1
-else
-    echo "Created Mercurial tag 'v$new'."
 fi
 
-source_release="$pkg-$new.tar.gz"
-
-if ! hg archive -r v$new "$source_release"; then
+echo "[2/6] Running 'hg archive'."
+if ! hg archive -t files -r v$new "$release"; then
     echo "Error running 'hg archive'."
     exit 1
-else
-    echo "Created $source_release."
 fi
 
-binary_release="$pkg-$new.jar"
-cp java/plume.jar "$binary_release"
-echo "Created $binary_release."
+echo "[3/6] Building plume-lib."
+export JAVAC_TARGET_FLAGS="-target 5"
+make -C "$release/java" all
+if [[ $? -ne 0 ]]; then
+    echo "Error building plume-lib."
+    exit 1;
+fi
+
+echo "[4/6] Performing post-build clean up."
+make -C "$release/java" release_clean
+if [[ $? -ne 0 ]]; then
+    echo "Error running 'make release_clean'."
+    exit 1;
+fi
+
+echo "[5/6] Creating release archive: $release_tar"
+tar czf "$release_tar" --owner=0 --group=0 "$release"
+
+echo "[6/6] Cleaning up."
+rm -rf "$release"
+
+done_release() {
+    echo ""
+    echo "Script complete."
+    echo "To finalize the release, perform the following steps manually:"
+    if ! $uploaded; then
+        echo "* Upload $release_tar to Google Code."
+    fi
+    echo "* Run 'hg push' to push the newly created tag."
+    exit 0
+}
+
+uploaded=false
+echo ""
+echo -n "Attempt to upload release to Google Code? [y/n]: "
+read answer
+
+ans=${answer:0:1}
+if [[ ! ($ans = "y" || $ans = "Y") ]]; then
+    done_release
+fi
 
 if ! which googlecode_upload.py &> /dev/null; then
-    echo "Release complete."
-    echo "Please run 'hg push' to push the new tag."
-    echo "Please upload artifacts to Google code."
-    exit 0
+    echo "Could not find googlecode_upload.py in PATH."
+    done_release
 fi
 
-echo -n "Enter your Google Code username: "
-read username
-echo -n "Enter your Google Code password: "
-read password
-
 googlecode_upload.py \
-    --summary "Plume-lib v$new source release" \
+    --summary "Plume-lib v$new release" \
     --project "plume-lib" \
-    --user "$username" \
-    --password "$password" \
     --labels "Type-Source" \
-    "$source_release" &&
-
-googlecode_upload.py \
-    --summary "Plume-lib v$new binary release (Java components)" \
-    --project "plume-lib" \
-    --user "$username" \
-    --password "$password" \
-    "$binary_release"
+    "$release_tar"
 
 if [[ $? -ne 0 ]] ; then
-    echo ""
-    echo "Uploading to Google Code failed"
-    echo "Please upload artifacts manually."
+    echo "Uploading to Google Code failed."
+    done_release
 fi
 
-echo ""
-echo "Release complete."
-echo "Please run 'hg push' to push the new tag."
+uploaded=true
+echo "Uploaded $release_tar to Google Code successfully."
+done_release
