Update release instructions

diff --git a/bin/make-plume-release b/bin/make-plume-release
--- a/bin/make-plume-release
+++ b/bin/make-plume-release
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Script that creates a plume-lib release and uploads artifacts to Google Code.
+# Script that creates a plume-lib release.
 
 # If you just want to make plume.jar for your own use, then instead use:
 #   make jar
@@ -9,9 +9,15 @@
 # You can also find a pre-built plume.jar in the plume-lib release, in a
 # file such as plume-lib-1.0.0/java/plume.jar .
 
-script=$(basename $0)
+# User customization
+GITHUB_TOKEN=`cat $HOME/private/github-plume-lib-token`
+GITHUB_USER=mernst
 
-pkg="plume-lib"
+GITHUB_REPO=plume-lib
+pkg=${GITHUB_REPO}
+
+# Argument processing
+script=$(basename $0)
 new=$1
 
 if [[ -z $new ]]; then
@@ -20,16 +26,16 @@ if [[ -z $new ]]; then
     exit 1
 fi
 
-if ! hg status &> /dev/null; then
-    echo "$PWD is not a mercurial repository."
+if ! git status 2>&1 /dev/null; then
+    echo "$PWD is not a Git repository."
 fi
 
-if [[ -n $(hg status -q) ]]; then
+if [[ -n $(git status -q) ]]; then
     echo "Uncommitted changes; commit and push changes before making a release."
     exit 1
 fi
 
-if hg outgoing &> /dev/null; then
+if git log --branches --not --remotes &> /dev/null; then
     echo "Unpushed changes; push changes before making a release."
     exit 1
 fi
@@ -51,16 +57,16 @@ fi
 release="$pkg-$new"
 release_tar="$release.tar.gz"
 
-echo "[1/6] Creating Mercurial tag 'v$new'."
-if ! hg tag v$new &> /dev/null; then
-    echo "Failed to create Mercurial tag 'v$new'."
-    echo "Run 'hg tags' to check if the tag already exists."
+echo "[1/6] Creating tag 'v$new'."
+if ! git tag v$new &> /dev/null; then
+    echo "Failed to create Git tag 'v$new'."
+    echo "Run 'git tag' to check if the tag already exists."
     exit 1
 fi
 
-echo "[2/6] Running 'hg archive'."
-if ! hg archive -t files -r v$new "$release"; then
-    echo "Error running 'hg archive'."
+echo "[2/6] Running 'git archive'."
+if ! git archive -t files -r v$new "$release"; then
+    echo "Error running 'git archive'."
     exit 1
 fi
 
@@ -92,36 +98,39 @@ done_release() {
     if ! $uploaded; then
         echo "* Upload $release_tar to Google Code."
     fi
-    echo "* Run 'hg push' to push the newly created tag."
+    echo "* Push the newly created tag by running:  git push --tags"
     exit 0
 }
 
 uploaded=false
-echo ""
-echo -n "Attempt to upload release to Google Code? [y/n]: "
-read answer
 
-ans=${answer:0:1}
-if [[ ! ($ans = "y" || $ans = "Y") ]]; then
-    done_release
-fi
+## TODO: convert this for GitHub
+# echo ""
+# echo -n "Attempt to upload release to Google Code? [y/n]: "
+# read answer
+# 
+# ans=${answer:0:1}
+# if [[ ! ($ans = "y" || $ans = "Y") ]]; then
+#     done_release
+# fi
+# 
+# if ! which googlecode_upload.py &> /dev/null; then
+#     echo "Could not find googlecode_upload.py in PATH."
+#     done_release
+# fi
+# 
+# googlecode_upload.py \
+#     --summary "Plume-lib v$new release" \
+#     --project "plume-lib" \
+#     --labels "Type-Source" \
+#     "$release_tar"
+# 
+# if [[ $? -ne 0 ]] ; then
+#     echo "Uploading to Google Code failed."
+#     done_release
+# fi
+# 
+# uploaded=true
+# echo "Uploaded $release_tar to Google Code successfully."
 
-if ! which googlecode_upload.py &> /dev/null; then
-    echo "Could not find googlecode_upload.py in PATH."
-    done_release
-fi
-
-googlecode_upload.py \
-    --summary "Plume-lib v$new release" \
-    --project "plume-lib" \
-    --labels "Type-Source" \
-    "$release_tar"
-
-if [[ $? -ne 0 ]] ; then
-    echo "Uploading to Google Code failed."
-    done_release
-fi
-
-uploaded=true
-echo "Uploaded $release_tar to Google Code successfully."
 done_release
